# Generated by Django 5.2.13 on 2026-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_phone', models.CharField(db_index=True, max_length=20)),
                ('verify_token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('telegram_user_id', models.CharField(blank=True, max_length=64)),
                ('otp_hash', models.CharField(blank=True, max_length=256)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['normalized_phone', 'created_at'], name='accounts_ph_normali_e285f5_idx')],
            },
        ),
    ]
