# Generated by Django 5.2.13 on 2026-05-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_longest_streak_achievement_rival'),
        ('questions', '0003_question_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Davom etmoqda'), ('completed', 'Tugadi')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_started', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_received', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_questions', models.PositiveIntegerField(default=20)),
                ('completed_questions', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('xp_bonus', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_goal_date')],
            },
        ),
        migrations.CreateModel(
            name='DuelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(default=-1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_answers', to='accounts.duel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_answers', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['answered_at'],
                'constraints': [models.UniqueConstraint(fields=('duel', 'user', 'question'), name='unique_duel_user_question_answer')],
            },
        ),
        migrations.CreateModel(
            name='DuelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_questions', to='accounts.duel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_questions', to='questions.question')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('duel', 'question'), name='unique_duel_question')],
            },
        ),
    ]
