# Generated by Django 5.2.14 on 2026-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_onboarding_completed_user_onboarding_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
