# Generated by Django 5.2.13 on 2026-05-30 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_token_version'),
        ('centers', '0011_alter_externalolympiadresult_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardproduct',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='centers.educationcenter'),
        ),
        migrations.AddField(
            model_name='rewardproduct',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rewardproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_products/'),
        ),
        migrations.AddField(
            model_name='rewardproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
