# Generated by Django 5.2.14 on 2026-06-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rewardproduct_center_rewardproduct_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardproduct',
            name='is_premium_only',
            field=models.BooleanField(default=False),
        ),
    ]
