# Generated by Django 5.2.14 on 2026-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_totp_enabled_user_totp_secret_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_premium_toggle', "Premium holat o'zgardi"), ('user_block', 'Foydalanuvchi bloklandi'), ('account_delete', "Hisob o'chirildi"), ('center_approve', 'Markaz tasdiqlandi'), ('center_reject', 'Markaz rad etildi'), ('olympiad_create', 'Olimpiada yaratildi'), ('olympiad_delete', "Olimpiada o'chirildi"), ('question_create', 'Savol yaratildi'), ('question_delete', "Savol o'chirildi"), ('member_approve', "A'zo tasdiqlandi"), ('member_reject', "A'zo rad etildi")], max_length=50),
        ),
    ]
