# Generated by Django 5.2.14 on 2026-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level_streak',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='subject_levels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
