# Generated by Django 5.2.14 on 2026-06-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_level_streak_user_subject_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
