# Generated by Django 5.2.14 on 2026-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_premium_trial_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
