# Generated by Django 5.2.14 on 2026-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_supportmessage_session_id_alter_supportmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('model', 'AI Yordamchi'), ('admin', 'Platform Admin')], max_length=10),
        ),
    ]
