# Generated by Django 5.2.14 on 2026-07-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_supportmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_manager_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_teacher_completed',
            field=models.BooleanField(default=False),
        ),
    ]
