# Generated by Django 5.2.14 on 2026-07-22 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPracticeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('subject', models.CharField(blank=True, default='', max_length=80)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_practice_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_practice_set_per_user_date')],
            },
        ),
    ]
