# Generated by Django 5.2.14 on 2026-07-22 00:40

import uuid
from django.db import migrations, models


def fill_portfolio_uuids(apps, schema_editor):
    """Mavjud userlarga noyob UUID beradi.

    Field callable default (uuid4) bilan qo'shilganda AddField barcha mavjud
    qatorlarga BIR XIL qiymat berib unique constraint'ni buzishi mumkin (ayniqsa
    SQLite'da). Shu sababli avval field unique'siz null bilan qo'shiladi, keyin
    shu data migration har bir qatorga alohida UUID yozadi, so'ng unique
    constraint qo'yiladi (keyingi AlterField). certificate_uuid naqshi kabi.
    """
    User = apps.get_model('accounts', 'User')
    seen = set()
    for user in User.objects.all().iterator(chunk_size=500):
        if user.portfolio_uuid is None or user.portfolio_uuid in seen:
            user.portfolio_uuid = uuid.uuid4()
            user.save(update_fields=['portfolio_uuid'])
        seen.add(user.portfolio_uuid)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_dailypracticeset'),
    ]

    operations = [
        # 1-qadam: field'ni unique'SIZ qo'shamiz (mavjud qatorlar NULL bo'ladi).
        migrations.AddField(
            model_name='user',
            name='portfolio_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        # 2-qadam: har bir mavjud qatorga noyob UUID beramiz.
        migrations.RunPython(fill_portfolio_uuids, noop_reverse),
        # 3-qadam: endi barcha qiymatlar noyob — unique constraint qo'yamiz.
        migrations.AlterField(
            model_name='user',
            name='portfolio_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
