# Generated by Django 5.2.14 on 2026-07-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_portfolio_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentStudentLink',
        ),
    ]
