# Generated by Django 5.2.14 on 2026-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_delete_parentstudentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypracticeset',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dailypracticeset',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
