# Generated by Django 5.2.14 on 2026-07-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_premium_toggle', "Premium holat o'zgardi"), ('user_block', 'Foydalanuvchi bloklandi'), ('user_role_change', "Foydalanuvchi rollari o'zgardi"), ('account_delete', "Hisob o'chirildi"), ('admin_password_reset', 'Parol majburan tiklandi'), ('admin_phone_change', "Telefon raqami o'zgartirildi"), ('admin_totp_reset', "2FA majburan o'chirildi"), ('admin_force_logout', 'Barcha seanslar yakunlandi'), ('center_approve', 'Markaz tasdiqlandi'), ('center_reject', 'Markaz rad etildi'), ('olympiad_create', 'Olimpiada yaratildi'), ('olympiad_delete', "Olimpiada o'chirildi"), ('question_create', 'Savol yaratildi'), ('question_delete', "Savol o'chirildi"), ('question_bulk_delete', "Savollar ommaviy o'chirildi"), ('question_archive', 'Savol arxivlandi'), ('member_approve', "A'zo tasdiqlandi"), ('member_reject', "A'zo rad etildi")], max_length=50),
        ),
    ]
