# Generated by Django 5.2.14 on 2026-07-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_user_block_reason_user_blocked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_premium_toggle', "Premium holat o'zgardi"), ('user_block', 'Foydalanuvchi bloklandi'), ('user_role_change', "Foydalanuvchi rollari o'zgardi"), ('account_delete', "Hisob o'chirildi"), ('admin_password_reset', 'Parol majburan tiklandi'), ('admin_phone_change', "Telefon raqami o'zgartirildi"), ('admin_totp_reset', "2FA majburan o'chirildi"), ('admin_force_logout', 'Barcha seanslar yakunlandi'), ('admin_impersonate_start', "Foydalanuvchi sifatida ko'rish boshlandi"), ('admin_impersonate_end', "Foydalanuvchi sifatida ko'rish yakunlandi"), ('center_approve', 'Markaz tasdiqlandi'), ('center_reject', 'Markaz rad etildi'), ('olympiad_create', 'Olimpiada yaratildi'), ('olympiad_delete', "Olimpiada o'chirildi"), ('question_create', 'Savol yaratildi'), ('question_delete', "Savol o'chirildi"), ('question_bulk_delete', "Savollar ommaviy o'chirildi"), ('question_archive', 'Savol arxivlandi'), ('member_approve', "A'zo tasdiqlandi"), ('member_reject', "A'zo rad etildi")], max_length=50),
        ),
    ]
