# Generated by Django 5.2.14 on 2026-07-28 18:12
#
# Do'st bilan duel (async, navbatma-navbat) funksiyasi butunlay olib
# tashlandi — jadvallar ham tushiriladi. DIQQAT: qaytarib bo'lmaydi, duel
# tarixi yo'qoladi. `DailyGoal` (0014 migratsiyada shu modellar bilan birga
# yaratilgan) TEGILMAYDI — u alohida, ishlayotgan funksiya.
#
# makemigrations avval har bir FK uchun alohida `RemoveField` chiqargan edi,
# lekin `duel` maydoni `DuelAnswer`/`DuelQuestion` ning Meta `UniqueConstraint`
# larida ishlatilgani uchun state qurishda FieldDoesNotExist bilan yiqilardi.
# Modellar baribir butunlay o'chirilayotgani uchun `DeleteModel` ni bog'liqlik
# tartibida (avval bolalar, keyin `Duel`) yozamiz — cheklovlar jadval bilan
# birga ketadi.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_auditlog_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuelAnswer',
        ),
        migrations.DeleteModel(
            name='DuelQuestion',
        ),
        migrations.DeleteModel(
            name='Duel',
        ),
    ]
