# Generated by Django 5.2.14 on 2026-07-29 11:08
#
# "Kunlik AI mashq to'plami" (Daily AI Practice Set) funksiyasi butunlay olib
# tashlandi — jadval ham tushiriladi. DIQQAT: qaytarib bo'lmaydi, barcha
# saqlangan kunlik mashq to'plamlari va o'quvchilar bergan javoblar deploy
# paytida butunlay yo'qoladi. Zarur bo'lsa deploydan OLDIN backup oling.
#
# `DailyQuestion`/`DailyQuestionAnswer` (kunlik savollar) va `DailyGoal`
# (kunlik maqsad) TEGILMAYDI — ular alohida, ishlayotgan funksiyalar.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_duelanswer_duel_remove_duelquestion_duel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPracticeSet',
        ),
    ]
