# Generated by Django 5.2.14 on 2026-08-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_premium_toggle', "Premium holat o'zgardi"), ('user_block', 'Foydalanuvchi bloklandi'), ('user_role_change', "Foydalanuvchi rollari o'zgardi"), ('account_delete', "Hisob o'chirildi"), ('admin_password_reset', 'Parol majburan tiklandi'), ('admin_account_delete', "Hisob admin tomonidan o'chirildi"), ('admin_content_delete', "Foydalanuvchi kontenti o'chirildi"), ('admin_phone_change', "Telefon raqami o'zgartirildi"), ('admin_totp_reset', "2FA majburan o'chirildi"), ('admin_force_logout', 'Barcha seanslar yakunlandi'), ('admin_force_logout_session', 'Bitta seans majburiy tugatildi'), ('admin_user_warn', 'Foydalanuvchiga ogohlantirish yuborildi'), ('admin_impersonate_start', "Foydalanuvchi sifatida ko'rish boshlandi"), ('admin_impersonate_end', "Foydalanuvchi sifatida ko'rish yakunlandi"), ('admin_user_merge', 'Hisoblar birlashtirildi'), ('admin_ip_block', 'IP manzil bloklandi'), ('admin_ip_unblock', 'IP bloki olib tashlandi'), ('center_approve', 'Markaz tasdiqlandi'), ('center_reject', 'Markaz rad etildi'), ('olympiad_create', 'Olimpiada yaratildi'), ('olympiad_delete', "Olimpiada o'chirildi"), ('question_create', 'Savol yaratildi'), ('question_delete', "Savol o'chirildi"), ('question_bulk_delete', "Savollar ommaviy o'chirildi"), ('question_archive', 'Savol arxivlandi'), ('member_approve', "A'zo tasdiqlandi"), ('member_reject', "A'zo rad etildi")], max_length=50),
        ),
    ]
