# Generated by Django 5.2.14 on 2026-08-15 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_seeded_premium_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='exam_block_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='exam_blocked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_premium_toggle', "Premium holat o'zgardi"), ('user_block', 'Foydalanuvchi bloklandi'), ('user_role_change', "Foydalanuvchi rollari o'zgardi"), ('account_delete', "Hisob o'chirildi"), ('admin_password_reset', 'Parol majburan tiklandi'), ('admin_account_delete', "Hisob admin tomonidan o'chirildi"), ('admin_content_delete', "Foydalanuvchi kontenti o'chirildi"), ('admin_phone_change', "Telefon raqami o'zgartirildi"), ('admin_totp_reset', "2FA majburan o'chirildi"), ('admin_force_logout', 'Barcha seanslar yakunlandi'), ('admin_force_logout_session', 'Bitta seans majburiy tugatildi'), ('admin_user_warn', 'Foydalanuvchiga ogohlantirish yuborildi'), ('admin_impersonate_start', "Foydalanuvchi sifatida ko'rish boshlandi"), ('admin_impersonate_end', "Foydalanuvchi sifatida ko'rish yakunlandi"), ('admin_user_merge', 'Hisoblar birlashtirildi'), ('admin_ip_block', 'IP manzil bloklandi'), ('admin_ip_unblock', 'IP bloki olib tashlandi'), ('center_approve', 'Markaz tasdiqlandi'), ('center_reject', 'Markaz rad etildi'), ('olympiad_create', 'Olimpiada yaratildi'), ('olympiad_delete', "Olimpiada o'chirildi"), ('question_create', 'Savol yaratildi'), ('question_delete', "Savol o'chirildi"), ('question_bulk_delete', "Savollar ommaviy o'chirildi"), ('question_archive', 'Savol arxivlandi'), ('member_approve', "A'zo tasdiqlandi"), ('member_reject', "A'zo rad etildi"), ('admin_exam_ban', 'Olimpiadalardan chetlatildi'), ('admin_exam_unban', 'Olimpiada taqiqi bekor qilindi'), ('admin_user_note_add', "Ichki eslatma qo'shildi"), ('admin_user_note_delete', "Ichki eslatma o'chirildi"), ('admin_user_tags_update', 'Admin teglari yangilandi'), ('admin_user_coins_adjust', "Tangalar balansi o'zgartirildi"), ('admin_attempt_retake', 'Testni qayta topshirishga ruxsat berildi'), ('admin_broadcast_message', 'Ommaviy xabarnoma yuborildi')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserAdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_admin_notes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_01713b_idx')],
            },
        ),
    ]
