# Generated by Django 5.2.14 on 2026-08-16 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_user_admin_tags_user_exam_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_discount_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_practice_quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_premium_toggle', "Premium holat o'zgardi"), ('user_block', 'Foydalanuvchi bloklandi'), ('user_role_change', "Foydalanuvchi rollari o'zgardi"), ('account_delete', "Hisob o'chirildi"), ('admin_password_reset', 'Parol majburan tiklandi'), ('admin_account_delete', "Hisob admin tomonidan o'chirildi"), ('admin_content_delete', "Foydalanuvchi kontenti o'chirildi"), ('admin_phone_change', "Telefon raqami o'zgartirildi"), ('admin_totp_reset', "2FA majburan o'chirildi"), ('admin_force_logout', 'Barcha seanslar yakunlandi'), ('admin_force_logout_session', 'Bitta seans majburiy tugatildi'), ('admin_user_warn', 'Foydalanuvchiga ogohlantirish yuborildi'), ('admin_impersonate_start', "Foydalanuvchi sifatida ko'rish boshlandi"), ('admin_impersonate_end', "Foydalanuvchi sifatida ko'rish yakunlandi"), ('admin_user_merge', 'Hisoblar birlashtirildi'), ('admin_ip_block', 'IP manzil bloklandi'), ('admin_ip_unblock', 'IP bloki olib tashlandi'), ('center_approve', 'Markaz tasdiqlandi'), ('center_reject', 'Markaz rad etildi'), ('olympiad_create', 'Olimpiada yaratildi'), ('olympiad_delete', "Olimpiada o'chirildi"), ('question_create', 'Savol yaratildi'), ('question_delete', "Savol o'chirildi"), ('question_bulk_delete', "Savollar ommaviy o'chirildi"), ('question_archive', 'Savol arxivlandi'), ('member_approve', "A'zo tasdiqlandi"), ('member_reject', "A'zo rad etildi"), ('admin_exam_ban', 'Olimpiadalardan chetlatildi'), ('admin_exam_unban', 'Olimpiada taqiqi bekor qilindi'), ('admin_user_note_add', "Ichki eslatma qo'shildi"), ('admin_user_note_delete', "Ichki eslatma o'chirildi"), ('admin_user_tags_update', 'Admin teglari yangilandi'), ('admin_user_coins_adjust', "Tangalar balansi o'zgartirildi"), ('admin_attempt_retake', 'Testni qayta topshirishga ruxsat berildi'), ('admin_broadcast_message', 'Ommaviy xabarnoma yuborildi'), ('admin_device_ban', 'Qurilma (Fingerprint) bloklandi'), ('admin_device_unban', 'Qurilma bloki olib tashlandi'), ('admin_transfer_center', "O'quv markazi o'zgartirildi"), ('admin_set_quota', 'Individual kvota va chegirma belgilandi'), ('admin_payment_refund', "To'lov qaytarildi (Refund)"), ('admin_send_telegram', "Telegram orqali to'g'ridan-to'g'ri xabar yuborildi"), ('admin_flash_alert', 'Shaxsiy modal xabar yuborildi'), ('admin_live_terminate', "Jonli imtihon majburan to'xtatildi"), ('admin_bulk_import_users', 'Foydalanuvchilar ommaviy import qilindi')], max_length=50),
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('streak', 'Streak bonusi'), ('daily_goal', 'Kunlik maqsad'), ('daily_question', 'Kunlik savol'), ('referral', 'Referral bonusi'), ('shop_redeem', 'Do‘kon xaridi'), ('admin_adjust', 'Admin to‘g‘rilashi'), ('olympiad_reward', 'Olimpiada mukofoti'), ('other', 'Boshqa')], db_index=True, default='other', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_co_user_id_2d19e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('browser_name', models.CharField(blank=True, default='', max_length=100)),
                ('os_name', models.CharField(blank=True, default='', max_length=100)),
                ('screen_resolution', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('is_banned', models.BooleanField(db_index=True, default=False)),
                ('ban_reason', models.CharField(blank=True, default='', max_length=255)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['fingerprint_hash'], name='accounts_de_fingerp_67b2c1_idx'), models.Index(fields=['user', '-last_seen_at'], name='accounts_de_user_id_df9765_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFlashAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('info', 'Ma‘lumot'), ('warning', 'Ogohlantirish'), ('urgent', 'Muhim / Shoshilinch'), ('success', 'Muvaffaqiyat')], default='info', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_flash_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', 'is_read'], name='accounts_us_user_id_1de468_idx')],
            },
        ),
    ]
