# Generated by Django 5.2.14 on 2026-08-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='Texnik ishlar rejimi')),
                ('maintenance_message', models.TextField(blank=True, default='Platformada rejali texnik ishlar olib borilmoqda. Tez orada qaytamiz!')),
                ('allow_registrations', models.BooleanField(default=True, help_text="Yangi foydalanuvchilar ro'yxatdan o'tishi")),
                ('default_ai_model', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('camera_proctoring_global', models.BooleanField(default=True, help_text='Global proktoring yoqilganligi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
