# Generated by Django 5.2.17 on 2026-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('account_link', 'Account link'), ('password_reset', 'Password reset'), ('appeal', 'Appeal')], db_index=True, default='registration', max_length=32),
        ),
    ]
