# Generated by Django 5.2.14 on 2026-08-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_remove_user_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_premium_toggle', "Premium holat o'zgardi"), ('user_block', 'Foydalanuvchi bloklandi'), ('user_role_change', "Foydalanuvchi rollari o'zgardi"), ('account_delete', "Hisob o'chirildi"), ('admin_password_reset', 'Parol majburan tiklandi'), ('admin_account_delete', "Hisob admin tomonidan o'chirildi"), ('admin_content_delete', "Foydalanuvchi kontenti o'chirildi"), ('admin_phone_change', "Telefon raqami o'zgartirildi"), ('admin_totp_reset', "2FA majburan o'chirildi"), ('admin_force_logout', 'Barcha seanslar yakunlandi'), ('admin_force_logout_session', 'Bitta seans majburiy tugatildi'), ('admin_user_warn', 'Foydalanuvchiga ogohlantirish yuborildi'), ('admin_impersonate_start', "Foydalanuvchi sifatida ko'rish boshlandi"), ('admin_impersonate_end', "Foydalanuvchi sifatida ko'rish yakunlandi"), ('admin_user_merge', 'Hisoblar birlashtirildi'), ('admin_ip_block', 'IP manzil bloklandi'), ('admin_ip_unblock', 'IP bloki olib tashlandi'), ('admin_appeal_review', "Appellyatsiya ko'rib chiqildi"), ('center_approve', 'Markaz tasdiqlandi'), ('center_reject', 'Markaz rad etildi'), ('olympiad_create', 'Olimpiada yaratildi'), ('olympiad_delete', "Olimpiada o'chirildi"), ('question_create', 'Savol yaratildi'), ('question_delete', "Savol o'chirildi"), ('question_bulk_delete', "Savollar ommaviy o'chirildi"), ('question_archive', 'Savol arxivlandi'), ('member_approve', "A'zo tasdiqlandi"), ('member_reject', "A'zo rad etildi"), ('admin_exam_ban', 'Olimpiadalardan chetlatildi'), ('admin_exam_unban', 'Olimpiada taqiqi bekor qilindi'), ('admin_user_note_add', "Ichki eslatma qo'shildi"), ('admin_user_note_delete', "Ichki eslatma o'chirildi"), ('admin_user_tags_update', 'Admin teglari yangilandi'), ('admin_user_coins_adjust', "Tangalar balansi o'zgartirildi"), ('admin_attempt_retake', 'Testni qayta topshirishga ruxsat berildi'), ('admin_broadcast_message', 'Ommaviy xabarnoma yuborildi'), ('admin_device_ban', 'Qurilma (Fingerprint) bloklandi'), ('admin_device_unban', 'Qurilma bloki olib tashlandi'), ('admin_transfer_center', "O'quv markazi o'zgartirildi"), ('admin_set_quota', 'Individual kvota va chegirma belgilandi'), ('admin_payment_refund', "To'lov qaytarildi (Refund)"), ('admin_send_telegram', "Telegram orqali to'g'ridan-to'g'ri xabar yuborildi"), ('admin_flash_alert', 'Shaxsiy modal xabar yuborildi'), ('admin_live_terminate', "Jonli imtihon majburan to'xtatildi"), ('manager_live_disqualify', 'Menejer jonli imtihonda diskvalifikatsiya qildi'), ('manager_live_remove', 'Menejer jonli imtihondan chiqarib yubordi'), ('admin_bulk_import_users', 'Foydalanuvchilar ommaviy import qilindi'), ('admin_django_admin_user_edit', 'Django admin orqali profil tahrirlandi'), ('admin_sensitive_data_view', "Maxfiy ma'lumot ko'rildi")], max_length=50),
        ),
    ]
