# Generated by Django 5.2.14 on 2026-08-16 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('pro_users', 'Faqat PRO (Obunachi) foydalanuvchilar'), ('inactive_7d', 'Oxirgi 7 kunda kirmaganlar'), ('students', 'Faqat O‘quvchilar'), ('teachers', 'Faqat O‘qituvchilar'), ('center_owners', 'Faqat Markaz egalari')], default='all', max_length=30)),
                ('send_telegram', models.BooleanField(default=True, help_text='Telegram ulaganlarga bot orqali yuborish')),
                ('send_in_app', models.BooleanField(default=True, help_text="Platforma ichida qo'ng'iroqcha xabarnomasi")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sent', 'Yuborildi'), ('failed', 'Xatolik')], default='draft', max_length=20)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('telegram_sent_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
