# Generated by Django 5.2.14 on 2026-08-04 06:58

# Yangi bayroq turi: `olympiad` — markaz xodimi shikoyat qilgan tadbir
# (olympiads/views.py: flag_olympiad). `question` bilan bir xil naqsh.
#
# 0002 dagidek sxema o'zgarmaydi: bu no-op AlterField (faqat `choices`).
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_moderationflag_flag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationflag',
            name='flag_type',
            field=models.CharField(choices=[('question', 'Savol'), ('olympiad', 'Olimpiada'), ('suspicious_ip', 'Shubhali IP'), ('warning_threshold', 'Ogohlantirishlar chegarasi')], db_index=True, max_length=20),
        ),
    ]
