# Generated by Django 5.2.17 on 2026-08-17 00:53

# Yangi bayroq turi: `appeal` — chora ko'rilgan foydalanuvchining rasmiy
# e'tirozi (accounts/views_appeals.py: submit_appeal).
#
# 0002/0003 dagidek sxema o'zgarmaydi: bu no-op AlterField (faqat `choices`).
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_blockedip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationflag',
            name='flag_type',
            field=models.CharField(choices=[('question', 'Savol'), ('olympiad', 'Olimpiada'), ('suspicious_ip', 'Shubhali IP'), ('warning_threshold', 'Ogohlantirishlar chegarasi'), ('appeal', 'Appellyatsiya')], db_index=True, max_length=20),
        ),
    ]
