# Generated by Django 5.2.14 on 2026-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='manager_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('student', 'Student'), ('organization', 'Organization')], default='student', max_length=20),
        ),
    ]
