# Generated by Django 5.2.14 on 2026-05-31 18:47

from django.db import migrations


def seed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    
    # Clean up existing plans first
    SubscriptionPlan.objects.all().delete()

    plans_data = []

    # --- Student Plans ---
    student_tiers = [
        {
            'name': 'Standart',
            'desc_prefix': 'O\'quvchilar uchun asosiy reja',
            'features': ["Barcha olimpiadalarda qatnashish", "Haftalik natijalar tahlili", "Telegram xabarnomalar"],
            'durations': [
                {'months': 1, 'days': 30, 'price': 9999.00, 'popular': False},
                {'months': 3, 'days': 90, 'price': 26999.00, 'popular': False},
                {'months': 6, 'days': 180, 'price': 47999.00, 'popular': False},
                {'months': 12, 'days': 365, 'price': 83999.00, 'popular': False},
            ]
        },
        {
            'name': 'Plus',
            'desc_prefix': 'O\'quvchilar uchun kengaytirilgan reja',
            'features': ["Standart reja imkoniyatlari", "AI tavsiyalar va yechimlar", "Haftalik PDF hisobotlar", "Reyting tahlili"],
            'durations': [
                {'months': 1, 'days': 30, 'price': 19999.00, 'popular': True},
                {'months': 3, 'days': 90, 'price': 53999.00, 'popular': True},
                {'months': 6, 'days': 180, 'price': 95999.00, 'popular': True},
                {'months': 12, 'days': 365, 'price': 167999.00, 'popular': True},
            ]
        },
        {
            'name': 'Pro',
            'desc_prefix': 'O\'quvchilar uchun to\'liq imkoniyatlar',
            'features': ["Plus reja imkoniyatlari", "AI shaxsiy o\'qituvchi", "Barcha olimpiadalar tarixi", "Cheksiz mashq qilish"],
            'durations': [
                {'months': 1, 'days': 30, 'price': 29999.00, 'popular': False},
                {'months': 3, 'days': 90, 'price': 80999.00, 'popular': False},
                {'months': 6, 'days': 180, 'price': 143999.00, 'popular': False},
                {'months': 12, 'days': 365, 'price': 251999.00, 'popular': False},
            ]
        }
    ]

    for tier in student_tiers:
        for dur in tier['durations']:
            label = f"{dur['months']} oy" if dur['months'] != 12 else "1 yil"
            plans_data.append({
                'name': f"{tier['name']} ({label})",
                'plan_type': 'student',
                'price': dur['price'],
                'duration_days': dur['days'],
                'description': f"{tier['desc_prefix']} ({label})",
                'features': tier['features'],
                'is_popular': dur['popular'],
                'is_active': True
            })

    # --- Organization Plans ---
    org_tiers = [
        {
            'name': 'Standart',
            'desc_prefix': 'Kichik tashkilotlar uchun mos reja',
            'features': ["1 ta tashkilot qo'shish", "Menejer boshqaruv paneli", "Olimpiadalar o'tkazish", "Asosiy tahlillar"],
            'durations': [
                {'months': 1, 'days': 30, 'price': 199999.00, 'popular': False},
                {'months': 3, 'days': 90, 'price': 539999.00, 'popular': False},
                {'months': 6, 'days': 180, 'price': 959999.00, 'popular': False},
                {'months': 12, 'days': 365, 'price': 1679999.00, 'popular': False},
            ]
        },
        {
            'name': 'Plus',
            'desc_prefix': 'O\'sib borayotgan tashkilotlar uchun',
            'features': ["Standart reja imkoniyatlari", "PDF hisobotlarni yuklash", "AI savollar generatori", "Batafsil tahlillar", "Telegram bot integratsiyasi"],
            'durations': [
                {'months': 1, 'days': 30, 'price': 399999.00, 'popular': True},
                {'months': 3, 'days': 90, 'price': 1079999.00, 'popular': True},
                {'months': 6, 'days': 180, 'price': 1919999.00, 'popular': True},
                {'months': 12, 'days': 365, 'price': 3359999.00, 'popular': True},
            ]
        },
        {
            'name': 'Pro',
            'desc_prefix': 'Yirik ta\'lim tashkilotlari uchun',
            'features': ["Plus reja imkoniyatlari", "Cheksiz olimpiada va o'quvchilar", "API kirish", "Maxsus qo'llab-quvvatlash", "Ota-onalar paneli"],
            'durations': [
                {'months': 1, 'days': 30, 'price': 799999.00, 'popular': False},
                {'months': 3, 'days': 90, 'price': 2159999.00, 'popular': False},
                {'months': 6, 'days': 180, 'price': 3839999.00, 'popular': False},
                {'months': 12, 'days': 365, 'price': 6719999.00, 'popular': False},
            ]
        }
    ]

    for tier in org_tiers:
        for dur in tier['durations']:
            label = f"{dur['months']} oy" if dur['months'] != 12 else "1 yil"
            plans_data.append({
                'name': f"{tier['name']} ({label})",
                'plan_type': 'organization',
                'price': dur['price'],
                'duration_days': dur['days'],
                'description': f"{tier['desc_prefix']} ({label})",
                'features': tier['features'],
                'is_popular': dur['popular'],
                'is_active': True
            })

    for p in plans_data:
        SubscriptionPlan.objects.create(
            name=p['name'],
            plan_type=p['plan_type'],
            price=p['price'],
            duration_days=p['duration_days'],
            description=p['description'],
            features=p['features'],
            is_popular=p['is_popular'],
            is_active=p['is_active']
        )


def remove_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    SubscriptionPlan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_paymenttransaction_manager_commission_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_plans, reverse_code=remove_plans),
    ]

