# Generated by Django 5.2.14 on 2026-06-03 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_update_pro_plan_decoy_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.subscriptionplan'),
        ),
    ]
