# Generated by Django 5.2.14 on 2026-06-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_temporary_promo_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
