# Generated by Django 5.2.14 on 2026-06-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_paymenttransaction_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='cancel_reason',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Xato'), ('cancelled', 'Bekor qilingan (refund)')], default='pending', max_length=20),
        ),
    ]
