# Generated by Django 5.2.14 on 2026-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_paymenttransaction_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(
                fields=['user', 'status'], name='paytx_user_status_idx',
            ),
        ),
    ]
