# Generated by Django 5.2.14 on 2026-06-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_paymenttransaction_paytx_user_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_olympiads_monthly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
