# Generated by Django 5.2.14 on 2026-06-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_user_premium_trial_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Retention va Premium analitikasi',
                'verbose_name_plural': 'Retention va Premium analitikasi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
