# Generated by Django 5.2.13 on 2026-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_testsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='cheating_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='testsession',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disqualified', 'Disqualified'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
