# Generated by Django 5.2.13 on 2026-05-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0007_testsession_device_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='attempts.testattempt')),
            ],
        ),
    ]
