# Generated by Django 5.2.13 on 2026-05-30 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0008_attemptaianalysis'),
        ('questions', '0004_question_code_template_question_expected_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(blank=True, default='')),
                ('code_language', models.CharField(blank=True, default='', max_length=30)),
                ('ai_code_review', models.TextField(blank=True, default='', help_text='AI tavsiyasi')),
                ('ai_code_score', models.IntegerField(blank=True, help_text='AI ball (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='attempts.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='questions.question')),
            ],
            options={
                'ordering': ['question_id'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_code_question')],
            },
        ),
    ]
