# Generated by Django 5.2.14 on 2026-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0009_codesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='all_tests_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
