# Generated by Django 5.2.14 on 2026-06-11 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0010_codesubmission_all_tests_passed'),
        ('olympiads', '0011_alter_olympiad_test_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['olympiad', 'status'], name='testsession_olymp_status_idx'),
        ),
    ]
