# Generated by Django 5.2.14 on 2026-06-17 11:11

import uuid
from django.db import migrations, models


def fill_certificate_uuids(apps, schema_editor):
    """Mavjud attempt'larga noyob UUID beradi.

    Field callable default (uuid4) bilan qo'shilganda AddField barcha mavjud
    qatorlarga BIR XIL qiymat berib unique constraint'ni buzishi mumkin. Shu
    sababli avval field unique'siz null bilan qo'shiladi, keyin shu data
    migration har bir qatorga alohida UUID yozadi, so'ng unique constraint
    qo'yiladi (keyingi AlterField operatsiyasi).
    """
    TestAttempt = apps.get_model('attempts', 'TestAttempt')
    # SQLite'da AddField barcha mavjud qatorlarga BIR XIL default qiymat berishi
    # mumkin — shu sababli NULL va takroriy UUID'larni ham qayta to'ldiramiz.
    seen = set()
    for attempt in TestAttempt.objects.all().iterator(chunk_size=500):
        if attempt.certificate_uuid is None or attempt.certificate_uuid in seen:
            attempt.certificate_uuid = uuid.uuid4()
            attempt.save(update_fields=['certificate_uuid'])
        seen.add(attempt.certificate_uuid)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0012_essaygrade'),
    ]

    operations = [
        # 1-qadam: field'ni unique'SIZ qo'shamiz (mavjud qatorlar NULL bo'ladi).
        migrations.AddField(
            model_name='testattempt',
            name='certificate_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        # 2-qadam: har bir mavjud qatorga noyob UUID beramiz.
        migrations.RunPython(fill_certificate_uuids, noop_reverse),
        # 3-qadam: endi barcha qiymatlar noyob — unique constraint qo'yamiz.
        migrations.AlterField(
            model_name='testattempt',
            name='certificate_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
