# Generated by Django 5.2.14 on 2026-07-21 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0013_testattempt_certificate_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testsession',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_test_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disqualified', 'Disqualified'), ('completed', 'Completed'), ('pending_review', 'Pending review')], default='active', max_length=20),
        ),
    ]
