# Generated by Django 5.2.14 on 2026-07-22 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0014_testsession_paused_seconds_and_more'),
        ('questions', '0010_question_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_ai_feedbacks', to='attempts.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_ai_feedbacks', to='questions.question')),
            ],
            options={
                'ordering': ['question_id'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_essay_ai_feedback')],
            },
        ),
    ]
