# Generated by Django 5.2.14 on 2026-07-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0015_essayaifeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='camera_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='camera_consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
