# Generated by Django 5.2.14 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0016_testsession_camera_consent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='microphone_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='microphone_consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
