# Generated by Django 5.2.14 on 2026-07-28 18:12
#
# Jonli viktorina ("Kahoot uslubidagi") va real-time duel funksiyalari olib
# tashlandi — ularning yakuniy natijalarini saqlagan jadvallar ham
# tushiriladi. DIQQAT: qaytarib bo'lmaydi, o'tgan o'yin natijalari yo'qoladi.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0019_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='host',
        ),
        migrations.DeleteModel(
            name='DuelResult',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
