# Generated by Django 5.2.17 on 2026-08-17 00:54

import attempts.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0021_codesubmission_evaluation_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, storage=attempts.storage.EvidenceStorage(), upload_to='camera/%Y/%m/%d/')),
                ('screen_image', models.FileField(blank=True, null=True, storage=attempts.storage.EvidenceStorage(), upload_to='screen/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(choices=[('flagged', "Bayroq qo'yildi (tekshiruv kutilmoqda)"), ('disqualified', 'Diskvalifikatsiya tasdiqlandi')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_snapshots', to='attempts.testsession')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['captured_at'], name='evidence_captured_idx')],
            },
        ),
    ]
