# Generated by Django 5.2.14 on 2026-08-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0022_evidencesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='cefr_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='ielts_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='section_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
