# Generated by Django 5.2.14 on 2026-08-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0023_testattempt_cefr_level_testattempt_ielts_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='listening_play_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
