# Generated by Django 5.2.14 on 2026-08-17 19:38

import attempts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0024_testsession_listening_play_counts'),
        ('olympiads', '0016_olympiad_exam_format'),
        ('questions', '0013_question_audio_question_audio_transcript_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(storage=attempts.storage.EvidenceStorage(), upload_to='speaking/%Y/%m/%d/')),
                ('content_type', models.CharField(blank=True, default='audio/webm', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answers', to='olympiads.olympiad')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answers', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'olympiad', 'question'), name='unique_speaking_answer')],
            },
        ),
    ]
