# Generated by Django 5.2.14 on 2026-08-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0025_speakinganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsession',
            name='removal_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disqualified', 'Disqualified'), ('completed', 'Completed'), ('pending_review', 'Pending review'), ('removed', 'Removed')], default='active', max_length=20),
        ),
    ]
