# Generated by Django 5.2.13 on 2026-05-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin'), ('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre-int', 'Pre-Intermediate'), ('int', 'Intermediate'), ('upper-int', 'Upper-Intermediate'), ('advanced', 'Advanced')], default='medium', max_length=10),
        ),
    ]
