# Generated by Django 5.2.13 on 2026-05-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_template',
            field=models.TextField(blank=True, default='', help_text="O'quvchiga beriluvchi boshlang'ich kod skelet"),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_output',
            field=models.TextField(blank=True, default='', help_text='Kutilgan natija (ustoz/menejer tekshirishi uchun)'),
        ),
        migrations.AddField(
            model_name='question',
            name='programming_language',
            field=models.CharField(blank=True, default='', help_text='python, javascript, java, cpp, c va h.k.', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Test (variantli)'), ('code', 'Kod (dasturlash)')], db_index=True, default='mcq', max_length=10),
        ),
    ]
