# Generated by Django 5.2.13 on 2026-05-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_code_template_question_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='[{"input": "5", "expected_output": "25", "is_hidden": false}]'),
        ),
    ]
