# Generated by Django 5.2.14 on 2026-06-03 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0012_centermembership_centers_cen_user_id_a11acf_idx'),
        ('questions', '0005_question_test_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['center', 'subject'], name='questions_q_center__10ac6f_idx'),
        ),
    ]
