# Generated by Django 5.2.14 on 2026-06-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_correct_text_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('manual', "Qo'lda"), ('ai', 'AI'), ('pdf', 'PDF'), ('import', 'Import (Excel/CSV)')], default='manual', max_length=10),
        ),
    ]
