# Generated by Django 5.2.14 on 2026-07-25 11:33
#
# Savol banki ikkiga bo'linadi: olimpiada (markaz bo'ylab umumiy) va jonli
# viktorina (o'qituvchining shaxsiy) savollari. Yangi `purpose` ustuni
# default='olympiad' bilan qo'shiladi — MAVJUD barcha qatorlar 'olympiad'
# qiymatini oladi va avvalgidek umumiy savol bankida ko'rinishda davom etadi
# (hech narsa yashirilmaydi va yangidan ochilmaydi).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='purpose',
            field=models.CharField(choices=[('olympiad', 'Olimpiada/Test uchun'), ('live_quiz', 'Jonli Viktorina uchun')], db_index=True, default='olympiad', max_length=20),
        ),
    ]
