# Generated by Django 5.2.14 on 2026-08-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='questions/audio/'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_transcript',
            field=models.TextField(blank=True, default='', help_text='Listening audio transkripti / tahlili'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_url',
            field=models.URLField(blank=True, default='', help_text='Tashqi audio havola yoki CDN', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='passage_text',
            field=models.TextField(blank=True, default='', help_text="Reading matni yoki topshiriq ko'rsatmasi"),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('', 'Umumiy'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], db_index=True, default='', max_length=20),
        ),
    ]
