# Generated by Django 5.2.13 on 2026-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_add_celery_beat_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='event_type',
            field=models.CharField(choices=[('olympiad', 'Olimpiada'), ('competition', 'Musobaqa')], db_index=True, default='competition', max_length=20),
        ),
    ]
