# Generated by Django 5.2.13 on 2026-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0003_olympiad_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('inactive', 'Nofaol'), ('active', 'Faol'), ('finished', 'Tugagan')], default='draft', max_length=10),
        ),
    ]
