# Generated by Django 5.2.13 on 2026-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0004_alter_olympiad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='test_level',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
