# Generated by Django 5.2.13 on 2026-05-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0005_olympiad_test_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='test_type',
            field=models.CharField(blank=True, choices=[('', 'Belgilanmagan'), ('multiple_choice', 'Multiple choice'), ('true_false', 'True/False'), ('short_answer', 'Qisqa javob'), ('mixed', 'Aralash')], default='', max_length=20),
        ),
    ]
