# Generated by Django 5.2.13 on 2026-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0006_olympiad_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
