# Generated by Django 5.2.13 on 2026-05-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0008_olympiad_group_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='allowed_languages',
            field=models.JSONField(blank=True, default=list, help_text="['python', 'javascript'] — bo'sh bo'lsa barcha til ruxsat"),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='it_category',
            field=models.CharField(blank=True, choices=[('', 'Belgilanmagan'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Full Stack'), ('general', 'Umumiy')], default='', max_length=30),
        ),
    ]
