# Generated by Django 5.2.14 on 2026-06-03 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0012_centermembership_centers_cen_user_id_a11acf_idx'),
        ('olympiads', '0009_olympiad_allowed_languages_olympiad_it_category'),
        ('questions', '0006_question_questions_q_center__10ac6f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['center', 'is_deleted', 'status'], name='olympiads_o_center__950414_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['status', 'is_deleted'], name='olympiads_o_status_5d3a67_idx'),
        ),
    ]
