# Generated by Django 5.2.14 on 2026-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0010_olympiad_olympiads_o_center__950414_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='test_type',
            field=models.CharField(blank=True, choices=[('', 'Belgilanmagan'), ('multiple_choice', 'Multiple choice'), ('true_false', 'True/False'), ('short_answer', 'Qisqa javob'), ('mixed', 'Aralash'), ('code_only', 'Faqat kod (dasturlash)')], default='', max_length=20),
        ),
    ]
