# Generated by Django 5.2.14 on 2026-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0011_alter_olympiad_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='start_reminder_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
