# Generated by Django 5.2.14 on 2026-07-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0012_olympiad_start_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='camera_proctoring_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
