# Generated by Django 5.2.14 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0013_olympiad_camera_proctoring_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='voice_proctoring_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
