# Generated by Django 5.2.14 on 2026-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0014_olympiad_voice_proctoring_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='certificate_template',
            field=models.CharField(blank=True, default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_leaderboard_frozen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
