# Generated by Django 5.2.14 on 2026-08-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0015_olympiad_certificate_template_olympiad_frozen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='exam_format',
            field=models.CharField(choices=[('standard', 'Standart'), ('ielts', 'IELTS Mock'), ('cefr', 'CEFR Mock')], db_index=True, default='standard', max_length=20),
        ),
    ]
