# Generated by Django 5.2.13 on 2026-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centermembership',
            name='approval_code',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
