# Generated by Django 5.2.13 on 2026-05-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_centermembership_approval_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='organization_type',
            field=models.CharField(db_index=True, default="O'quv markaz", max_length=80),
        ),
    ]
