# Generated by Django 5.2.13 on 2026-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_educationcenter_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='country',
            field=models.CharField(db_index=True, default="O'zbekiston", max_length=80),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
