# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_educationcenter_country_educationcenter_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='centers/'),
        ),
    ]
