# Generated by Django 5.2.13 on 2026-05-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_educationcenter_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterRatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='centers.educationcenter')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('center', 'date'), name='unique_center_rating_date')],
            },
        ),
    ]
