# Generated by Django 5.2.14 on 2026-06-03 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_alter_externalolympiadresult_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='centermembership',
            index=models.Index(fields=['user', 'role', 'status'], name='centers_cen_user_id_a11acf_idx'),
        ),
    ]
