# Generated by Django 5.2.14 on 2026-06-08 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0012_centermembership_centers_cen_user_id_a11acf_idx'),
        ('olympiads', '0011_alter_olympiad_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockolympiad',
            name='source_olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_mocks', to='olympiads.olympiad'),
        ),
    ]
