# Generated by Django 5.2.14 on 2026-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0013_mockolympiad_source_olympiad'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcenter',
            name='brand_color',
            field=models.CharField(blank=True, default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='educationcenter',
            name='custom_domain',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
