# Generated by Django 5.2.14 on 2026-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0014_educationcenter_brand_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Kutilmoqda'),
                    ('approved', 'Tasdiqlandi'),
                    ('rejected', 'Rad etildi'),
                ],
                db_index=True,
                default='pending',
                max_length=10,
            ),
        ),
    ]
