# Generated by Django 5.2.14 on 2026-06-18 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0016_alter_educationcenter_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcenter',
            name='brand_color',
            field=models.CharField(blank=True, default='#6366f1', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', "Rang #RRGGBB formatida bo'lishi kerak")]),
        ),
    ]
