# Generated by Django 5.2.14 on 2026-07-30 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0017_alter_educationcenter_brand_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='centermembership',
            index=models.Index(fields=['center', 'role', 'status'], name='centers_cen_center__3faced_idx'),
        ),
    ]
